services:
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    network_mode: "host"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

  minikeyvalue:
    build:
      context: ./minikeyvalue
      dockerfile: Dockerfile
    volumes:
      - /mnt/raid5/kvstore1:/tmp
    ports:
      - "3000-3005:3000-3005"
    network_mode: "host"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"

  connect:
    build: .
    restart: unless-stopped
    ports:
      - "3222:3222"
      - "3223:3223"
      - "3111:3111"
      - "3112:3112"
    depends_on:
      - db
      # - redis
      - minikeyvalue
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - cargo-cache:/usr/local/cargo
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "10"

volumes:
  pgdata:
  cargo-cache:
  connect-target:
